- name: Reboot_raspberry
  ansible.builtin.reboot:
    msg: "Raspberry boot config changed"
    connect_timeout: 5
    reboot_timeout: 300
  when: (ansible_lsb.id is defined and ansible_lsb.id == "Raspbian") or (ansible_model is defined and "Raspberry Pi" in ansible_model)
