- name: Update PM2 globally
  npm:
    name: pm2
    global: true
    state: latest
  become: false

- name: Update PM2 in-memory
  command: "{{ ansible_facts['env']['HOME'] }}/.npm-global/bin/pm2 update"
  register: pm2_update
  changed_when: "'All PM2 processes have been restarted' in pm2_update.stdout"
  become: false
