- name: Update Minecraft server repository
  git:
    repo: git@github.com:bolinocroustibat/minecraft-server.git
    dest: "{{ user_home }}/minecraft-server"
    accept_hostkey: true
    update: true
    version: main
