- name: Include Wg-Easy secrets
  include_vars: secrets.yaml

- name: Create Wg-Easy configuration directory
  file:
    path: "/opt/wg-easy"
    state: directory
    mode: u=rwx,g=,o= # 700 (only the user can read, write and execute)

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "/opt/wg-easy/docker-compose.yml"
    mode: u=rw,g=r,o=r # 644 (read and write access for the owner of the file and read access for group and others)
  notify: recreate wg-easy container

- name: Start Wg-Easy container
  community.docker.docker_compose_v2:
    project_src: "/opt/wg-easy"
    state: present
    remove_orphans: true
    build: "never"
    pull: "always"
    recreate: always

- name: Check if DNS is properly configured
  command: dig +short {{ wg_easy__domain }}
  register: wg_easy_dns_check
  changed_when: false
  failed_when: wg_easy_dns_check.stdout == ""

- name: Check if SSL certificate exists
  stat:
    path: "/etc/letsencrypt/live/{{ wg_easy__domain }}/fullchain.pem"
  register: wg_easy_ssl_cert_exists

- name: Deploy Nginx vhost for Wg-Easy (only if SSL doesn't exist)
  template:
    src: "{{ wg_easy__domain }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ wg_easy__domain }}.conf"
    mode: u=rw,g=r,o=r  # 644
  notify: Reload nginx config
  when: not wg_easy_ssl_cert_exists.stat.exists

- name: Enable Nginx vhost for Wg-Easy (only if SSL doesn't exist)
  file:
    src: "/etc/nginx/sites-available/{{ wg_easy__domain }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ wg_easy__domain }}.conf"
    state: link
    force: true
  notify: Reload nginx config
  when: not wg_easy_ssl_cert_exists.stat.exists

- name: Configure SSL with Certbot (only if SSL doesn't exist)
  command: certbot --nginx -d {{ wg_easy__domain }} --non-interactive --agree-tos --email me@adriencarpentier.com
  args:
    creates: "/etc/letsencrypt/live/{{ wg_easy__domain }}/fullchain.pem"
  when: wg_easy_dns_check.stdout != "" and not wg_easy_ssl_cert_exists.stat.exists
