- name: Reload nginx config
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true

- name: Restart transmission-daemon
  ansible.builtin.service:
    name: transmission-daemon
    state: restarted
  become: true
