- name: Check if ZSH is installed
  block:
    - name: Check if ZSH is installed with homebrew
      when: ansible_os_family == "Darwin"
      homebrew:
        name: zsh
        state: present
      register: zsh_installed

    - name: Check if ZSH is installed with apt
      when: ansible_os_family == "Debian"
      apt:
        name: zsh
        state: present
        update_cache: true
      become: true
      register: zsh_installed

- name: Install ZSH
  when: not zsh_installed.changed
  block:
    - name: Install ZSH with homebrew
      when: ansible_os_family == "Darwin"
      homebrew:
        name: zsh
        state: latest

    - name: Install ZSH with apt
      when: ansible_os_family == "Debian"
      apt:
        name: zsh
        state: latest
        update_cache: true
      become: true

- name: Install ZSH autosuggestions
  block:
    - name: Install ZSH autosuggestions with homebrew
      when: ansible_os_family == "Darwin"
      homebrew:
        name: zsh-autosuggestions
        state: latest

    - name: Install ZSH syntax highlighting with git clone
      when: ansible_os_family == "Debian"
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: "{{ user_home }}/.zsh/zsh-syntax-highlighting"
        clone: yes
        update: yes

- name: Install ZSH syntax highlighting
  block:
    - name: Install ZSH syntax highlighting with homebrew
      when: ansible_os_family == "Darwin"
      homebrew:
        name: zsh-autosuggestions
        state: latest

    - name: Install ZSH syntax highlighting with git clone
      when: ansible_os_family == "Debian"
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: "{{ user_home }}/.zsh/zsh-syntax-highlighting"
        clone: yes
        update: yes

- name: Backup existing .zshrc if it exists
  copy:
    remote_src: true
    src: "{{ user_home }}/.zshrc"
    dest: "{{ user_home }}/.zshrc_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve # Preserve the file permissions of the original file

- name: Write .zshrc
  template:
    src: .zshrc.j2
    dest: "{{ user_home }}/.zshrc"
    mode: "u=rw,g=r,o=r" # 644 (read and write access for the owner of the file and read access for group and others)

- name: Change current user shell to ZSH
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
