- name: Include Uptime Kuma secrets
  include_vars: secrets.yaml

- name: Ensure Uptime Kuma directory exists
  file:
    path: "/opt/uptime-kuma"
    state: directory
    mode: u=rwx,g=,o= # 700 (only the user can read, write and execute)

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "/opt/uptime-kuma/docker-compose.yml"
    mode: u=rw,g=r,o=r # 644

- name: Stop and remove existing Uptime Kuma container
  community.docker.docker_container:
    name: uptime-kuma
    state: absent
  ignore_errors: true

- name: Recreate Uptime Kuma container with new image
  community.docker.docker_compose_v2:
    project_src: "/opt/uptime-kuma"
    state: present
    remove_orphans: true
    build: "never"
    pull: "always"
    recreate: always
