- name: Install p10K with git clone
  ansible.builtin.git:
    repo: "git@github.com:romkatv/powerlevel10k.git"
    dest: "{{ user_home }}/.config/powerlevel10k/powerlevel10k.zsh-theme"
    clone: true
    update: true

- name: Backup existing .zshrc if it exists
  copy:
    remote_src: true
    src: "{{ user_home }}/.zshrc"
    dest: "{{ user_home }}/.zshrc_{{ ansible_facts['date_time']['iso8601'] }}.bak"
    mode: preserve # Preserve the file permissions of the original file

- name: Add p10k startup command to .zshrc
  command: "echo '# p10k #\nsource {{ user_home }}/.config/powerlevel10k/powerlevel10k.zsh-theme' >> {{ user_home }}/.zshrc"

- name: Reload ZSH config
  command: "source {{ user_home }}/.zshrc"
